# syntax = docker/dockerfile:1

ARG BUN_VERSION=1.2.2
FROM oven/bun:${BUN_VERSION}-slim AS base

WORKDIR /usr/src/app

FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json bun.lockb /temp/dev/
COPY packages/ui/package.json /temp/dev/packages/ui/
COPY packages/sdk/package.json /temp/dev/packages/sdk/
COPY web-landing/package.json /temp/dev/web-landing/
COPY web-app/package.json /temp/dev/web-app/
RUN cd /temp/dev && bun install --frozen-lockfile

RUN mkdir -p /temp/prod
COPY package.json bun.lockb /temp/prod/
COPY packages/ui/package.json /temp/prod/packages/ui/
COPY packages/sdk/package.json /temp/prod/packages/sdk/
COPY web-landing/package.json /temp/prod/web-landing/
COPY web-app/package.json /temp/prod/web-app/
RUN cd /temp/prod && bun install --frozen-lockfile --production

FROM base AS prerelease
COPY --from=install /temp/dev/node_modules node_modules
COPY . .

ARG VITE_WEB_API_URL
ARG VITE_WEB_MARKETING_URL
ENV NODE_ENV=production
RUN cd /usr/src/app/web-app && bun run build

FROM nginx:alpine AS release

COPY --from=prerelease /usr/src/app/web-app/dist /usr/share/nginx/html
COPY --from=prerelease /usr/src/app/nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
