# fly.toml app configuration file generated for dev-as-landing on 2025-02-11T17:02:36+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'dev-as-landing'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile.web-landing'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[services]]
  protocol = 'tcp'
  internal_port = 80

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
