/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as CreateProjectIndexImport } from './routes/create-project/index'
import { Route as LayoutIndexImport } from './routes/_layout.index'
import { Route as authLayoutImport } from './routes/(auth)/_layout'
import { Route as ProjectSlugLayoutImport } from './routes/$projectSlug/_layout'
import { Route as ProjectSlugLayoutIndexImport } from './routes/$projectSlug/_layout.index'
import { Route as authLayoutSignUpImport } from './routes/(auth)/_layout.sign-up'
import { Route as authLayoutLoginImport } from './routes/(auth)/_layout.login'

// Create Virtual Routes

const authImport = createFileRoute('/(auth)')()
const ProjectSlugImport = createFileRoute('/$projectSlug')()

// Create/Update Routes

const authRoute = authImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRoute,
} as any)

const ProjectSlugRoute = ProjectSlugImport.update({
  id: '/$projectSlug',
  path: '/$projectSlug',
  getParentRoute: () => rootRoute,
} as any)

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const CreateProjectIndexRoute = CreateProjectIndexImport.update({
  id: '/create-project/',
  path: '/create-project/',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const authLayoutRoute = authLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => authRoute,
} as any)

const ProjectSlugLayoutRoute = ProjectSlugLayoutImport.update({
  id: '/_layout',
  getParentRoute: () => ProjectSlugRoute,
} as any)

const ProjectSlugLayoutIndexRoute = ProjectSlugLayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectSlugLayoutRoute,
} as any)

const authLayoutSignUpRoute = authLayoutSignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authLayoutRoute,
} as any)

const authLayoutLoginRoute = authLayoutLoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/$projectSlug': {
      id: '/$projectSlug'
      path: '/$projectSlug'
      fullPath: '/$projectSlug'
      preLoaderRoute: typeof ProjectSlugImport
      parentRoute: typeof rootRoute
    }
    '/$projectSlug/_layout': {
      id: '/$projectSlug/_layout'
      path: '/$projectSlug'
      fullPath: '/$projectSlug'
      preLoaderRoute: typeof ProjectSlugLayoutImport
      parentRoute: typeof ProjectSlugRoute
    }
    '/(auth)': {
      id: '/(auth)'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/_layout': {
      id: '/(auth)/_layout'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authLayoutImport
      parentRoute: typeof authRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/create-project/': {
      id: '/create-project/'
      path: '/create-project'
      fullPath: '/create-project'
      preLoaderRoute: typeof CreateProjectIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/_layout/login': {
      id: '/(auth)/_layout/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLayoutLoginImport
      parentRoute: typeof authLayoutImport
    }
    '/(auth)/_layout/sign-up': {
      id: '/(auth)/_layout/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authLayoutSignUpImport
      parentRoute: typeof authLayoutImport
    }
    '/$projectSlug/_layout/': {
      id: '/$projectSlug/_layout/'
      path: '/'
      fullPath: '/$projectSlug/'
      preLoaderRoute: typeof ProjectSlugLayoutIndexImport
      parentRoute: typeof ProjectSlugLayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

interface ProjectSlugLayoutRouteChildren {
  ProjectSlugLayoutIndexRoute: typeof ProjectSlugLayoutIndexRoute
}

const ProjectSlugLayoutRouteChildren: ProjectSlugLayoutRouteChildren = {
  ProjectSlugLayoutIndexRoute: ProjectSlugLayoutIndexRoute,
}

const ProjectSlugLayoutRouteWithChildren =
  ProjectSlugLayoutRoute._addFileChildren(ProjectSlugLayoutRouteChildren)

interface ProjectSlugRouteChildren {
  ProjectSlugLayoutRoute: typeof ProjectSlugLayoutRouteWithChildren
}

const ProjectSlugRouteChildren: ProjectSlugRouteChildren = {
  ProjectSlugLayoutRoute: ProjectSlugLayoutRouteWithChildren,
}

const ProjectSlugRouteWithChildren = ProjectSlugRoute._addFileChildren(
  ProjectSlugRouteChildren,
)

interface authLayoutRouteChildren {
  authLayoutLoginRoute: typeof authLayoutLoginRoute
  authLayoutSignUpRoute: typeof authLayoutSignUpRoute
}

const authLayoutRouteChildren: authLayoutRouteChildren = {
  authLayoutLoginRoute: authLayoutLoginRoute,
  authLayoutSignUpRoute: authLayoutSignUpRoute,
}

const authLayoutRouteWithChildren = authLayoutRoute._addFileChildren(
  authLayoutRouteChildren,
)

interface authRouteChildren {
  authLayoutRoute: typeof authLayoutRouteWithChildren
}

const authRouteChildren: authRouteChildren = {
  authLayoutRoute: authLayoutRouteWithChildren,
}

const authRouteWithChildren = authRoute._addFileChildren(authRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/$projectSlug': typeof ProjectSlugLayoutRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/create-project': typeof CreateProjectIndexRoute
  '/login': typeof authLayoutLoginRoute
  '/sign-up': typeof authLayoutSignUpRoute
  '/$projectSlug/': typeof ProjectSlugLayoutIndexRoute
}

export interface FileRoutesByTo {
  '/$projectSlug': typeof ProjectSlugLayoutIndexRoute
  '/': typeof LayoutIndexRoute
  '/create-project': typeof CreateProjectIndexRoute
  '/login': typeof authLayoutLoginRoute
  '/sign-up': typeof authLayoutSignUpRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/$projectSlug': typeof ProjectSlugRouteWithChildren
  '/$projectSlug/_layout': typeof ProjectSlugLayoutRouteWithChildren
  '/(auth)': typeof authRouteWithChildren
  '/(auth)/_layout': typeof authLayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/create-project/': typeof CreateProjectIndexRoute
  '/(auth)/_layout/login': typeof authLayoutLoginRoute
  '/(auth)/_layout/sign-up': typeof authLayoutSignUpRoute
  '/$projectSlug/_layout/': typeof ProjectSlugLayoutIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/$projectSlug'
    | '/'
    | '/create-project'
    | '/login'
    | '/sign-up'
    | '/$projectSlug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/$projectSlug' | '/' | '/create-project' | '/login' | '/sign-up'
  id:
    | '__root__'
    | '/_layout'
    | '/$projectSlug'
    | '/$projectSlug/_layout'
    | '/(auth)'
    | '/(auth)/_layout'
    | '/_layout/'
    | '/create-project/'
    | '/(auth)/_layout/login'
    | '/(auth)/_layout/sign-up'
    | '/$projectSlug/_layout/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  ProjectSlugRoute: typeof ProjectSlugRouteWithChildren
  authRoute: typeof authRouteWithChildren
  CreateProjectIndexRoute: typeof CreateProjectIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  ProjectSlugRoute: ProjectSlugRouteWithChildren,
  authRoute: authRouteWithChildren,
  CreateProjectIndexRoute: CreateProjectIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout",
        "/$projectSlug",
        "/(auth)",
        "/create-project/"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/"
      ]
    },
    "/$projectSlug": {
      "filePath": "$projectSlug",
      "children": [
        "/$projectSlug/_layout"
      ]
    },
    "/$projectSlug/_layout": {
      "filePath": "$projectSlug/_layout.tsx",
      "parent": "/$projectSlug",
      "children": [
        "/$projectSlug/_layout/"
      ]
    },
    "/(auth)": {
      "filePath": "(auth)",
      "children": [
        "/(auth)/_layout"
      ]
    },
    "/(auth)/_layout": {
      "filePath": "(auth)/_layout.tsx",
      "parent": "/(auth)",
      "children": [
        "/(auth)/_layout/login",
        "/(auth)/_layout/sign-up"
      ]
    },
    "/_layout/": {
      "filePath": "_layout.index.tsx",
      "parent": "/_layout"
    },
    "/create-project/": {
      "filePath": "create-project/index.tsx"
    },
    "/(auth)/_layout/login": {
      "filePath": "(auth)/_layout.login.tsx",
      "parent": "/(auth)/_layout"
    },
    "/(auth)/_layout/sign-up": {
      "filePath": "(auth)/_layout.sign-up.tsx",
      "parent": "/(auth)/_layout"
    },
    "/$projectSlug/_layout/": {
      "filePath": "$projectSlug/_layout.index.tsx",
      "parent": "/$projectSlug/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
